# Generated by Django 5.0 on 2023-12-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='orderdetails',
            options={'verbose_name_plural': 'Order details'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='address',
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
