# Generated by Django 5.0 on 2023-12-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_alter_orderdetails_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
