# Generated by Django 5.0 on 2023-12-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_tag_products_image_products_slug_products_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='tags',
            field=models.ManyToManyField(to='store.tag'),
        ),
    ]
