# Generated by Django 5.0.2 on 2024-03-31 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comments',
        ),
    ]
